/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleRenterRouteImport } from './routes/$locale/_renter'
import { Route as LocaleBusinessRouteImport } from './routes/$locale/_business'
import { Route as LocaleVehiclesIndexRouteImport } from './routes/$locale/vehicles/index'
import { Route as LocaleRenterBookingsRouteImport } from './routes/$locale/_renter/bookings'
import { Route as LocaleBusinessDashboardRouteImport } from './routes/$locale/_business/dashboard'
import { Route as LocaleVehiclesClassesSlugRouteImport } from './routes/$locale/vehicles/classes/$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRenterRoute = LocaleRenterRouteImport.update({
  id: '/_renter',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBusinessRoute = LocaleBusinessRouteImport.update({
  id: '/_business',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVehiclesIndexRoute = LocaleVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRenterBookingsRoute = LocaleRenterBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LocaleRenterRoute,
} as any)
const LocaleBusinessDashboardRoute = LocaleBusinessDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleBusinessRoute,
} as any)
const LocaleVehiclesClassesSlugRoute =
  LocaleVehiclesClassesSlugRouteImport.update({
    id: '/vehicles/classes/$slug',
    path: '/vehicles/classes/$slug',
    getParentRoute: () => LocaleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/bookings': typeof LocaleRenterBookingsRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/bookings': typeof LocaleRenterBookingsRoute
  '/$locale/vehicles': typeof LocaleVehiclesIndexRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_business': typeof LocaleBusinessRouteWithChildren
  '/$locale/_renter': typeof LocaleRenterRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_business/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/_renter/bookings': typeof LocaleRenterBookingsRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/'
    | '/$locale/dashboard'
    | '/$locale/bookings'
    | '/$locale/vehicles/'
    | '/$locale/vehicles/classes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/dashboard'
    | '/$locale/bookings'
    | '/$locale/vehicles'
    | '/$locale/vehicles/classes/$slug'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_business'
    | '/$locale/_renter'
    | '/$locale/login'
    | '/$locale/'
    | '/$locale/_business/dashboard'
    | '/$locale/_renter/bookings'
    | '/$locale/vehicles/'
    | '/$locale/vehicles/classes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter': {
      id: '/$locale/_renter'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRenterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_business': {
      id: '/$locale/_business'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleBusinessRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/vehicles/': {
      id: '/$locale/vehicles/'
      path: '/vehicles'
      fullPath: '/$locale/vehicles/'
      preLoaderRoute: typeof LocaleVehiclesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter/bookings': {
      id: '/$locale/_renter/bookings'
      path: '/bookings'
      fullPath: '/$locale/bookings'
      preLoaderRoute: typeof LocaleRenterBookingsRouteImport
      parentRoute: typeof LocaleRenterRoute
    }
    '/$locale/_business/dashboard': {
      id: '/$locale/_business/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleBusinessDashboardRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/vehicles/classes/$slug': {
      id: '/$locale/vehicles/classes/$slug'
      path: '/vehicles/classes/$slug'
      fullPath: '/$locale/vehicles/classes/$slug'
      preLoaderRoute: typeof LocaleVehiclesClassesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleBusinessRouteChildren {
  LocaleBusinessDashboardRoute: typeof LocaleBusinessDashboardRoute
}

const LocaleBusinessRouteChildren: LocaleBusinessRouteChildren = {
  LocaleBusinessDashboardRoute: LocaleBusinessDashboardRoute,
}

const LocaleBusinessRouteWithChildren = LocaleBusinessRoute._addFileChildren(
  LocaleBusinessRouteChildren,
)

interface LocaleRenterRouteChildren {
  LocaleRenterBookingsRoute: typeof LocaleRenterBookingsRoute
}

const LocaleRenterRouteChildren: LocaleRenterRouteChildren = {
  LocaleRenterBookingsRoute: LocaleRenterBookingsRoute,
}

const LocaleRenterRouteWithChildren = LocaleRenterRoute._addFileChildren(
  LocaleRenterRouteChildren,
)

interface LocaleRouteChildren {
  LocaleBusinessRoute: typeof LocaleBusinessRouteWithChildren
  LocaleRenterRoute: typeof LocaleRenterRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleVehiclesIndexRoute: typeof LocaleVehiclesIndexRoute
  LocaleVehiclesClassesSlugRoute: typeof LocaleVehiclesClassesSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBusinessRoute: LocaleBusinessRouteWithChildren,
  LocaleRenterRoute: LocaleRenterRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleVehiclesIndexRoute: LocaleVehiclesIndexRoute,
  LocaleVehiclesClassesSlugRoute: LocaleVehiclesClassesSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
