/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSearchRouteImport } from './routes/$locale/search'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleRenterRouteImport } from './routes/$locale/_renter'
import { Route as LocaleBusinessRouteImport } from './routes/$locale/_business'
import { Route as LocaleVehiclesIndexRouteImport } from './routes/$locale/vehicles/index'
import { Route as ProviderInviteTokenRouteImport } from './routes/provider/invite/$token'
import { Route as LocaleStorefrontsLocationIdRouteImport } from './routes/$locale/storefronts/$locationId'
import { Route as LocaleProviderLoginRouteImport } from './routes/$locale/provider/login'
import { Route as LocaleManageOperatorSlugRouteImport } from './routes/$locale/manage/$operatorSlug'
import { Route as LocaleRenterDocumentsRouteImport } from './routes/$locale/_renter/documents'
import { Route as LocaleRenterBookingsRouteImport } from './routes/$locale/_renter/bookings'
import { Route as LocaleBusinessDashboardRouteImport } from './routes/$locale/_business/dashboard'
import { Route as LocaleRenterBookingsIndexRouteImport } from './routes/$locale/_renter/bookings/index'
import { Route as LocaleVehiclesClassesSlugRouteImport } from './routes/$locale/vehicles/classes/$slug'
import { Route as LocaleProviderInviteTokenRouteImport } from './routes/$locale/provider/invite/$token'
import { Route as LocaleManageOperatorSlugDashboardRouteImport } from './routes/$locale/manage/$operatorSlug/dashboard'
import { Route as LocaleRenterBookingsNewRouteImport } from './routes/$locale/_renter/bookings/new'
import { Route as LocaleRenterBookingsConfirmationRouteImport } from './routes/$locale/_renter/bookings/confirmation'
import { Route as LocaleBusinessManageBookingsRouteImport } from './routes/$locale/_business/manage/bookings'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRenterRoute = LocaleRenterRouteImport.update({
  id: '/_renter',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBusinessRoute = LocaleBusinessRouteImport.update({
  id: '/_business',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVehiclesIndexRoute = LocaleVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => LocaleRoute,
} as any)
const ProviderInviteTokenRoute = ProviderInviteTokenRouteImport.update({
  id: '/provider/invite/$token',
  path: '/provider/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleStorefrontsLocationIdRoute =
  LocaleStorefrontsLocationIdRouteImport.update({
    id: '/storefronts/$locationId',
    path: '/storefronts/$locationId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProviderLoginRoute = LocaleProviderLoginRouteImport.update({
  id: '/provider/login',
  path: '/provider/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleManageOperatorSlugRoute =
  LocaleManageOperatorSlugRouteImport.update({
    id: '/manage/$operatorSlug',
    path: '/manage/$operatorSlug',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleRenterDocumentsRoute = LocaleRenterDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LocaleRenterRoute,
} as any)
const LocaleRenterBookingsRoute = LocaleRenterBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LocaleRenterRoute,
} as any)
const LocaleBusinessDashboardRoute = LocaleBusinessDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleBusinessRoute,
} as any)
const LocaleRenterBookingsIndexRoute =
  LocaleRenterBookingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleRenterBookingsRoute,
  } as any)
const LocaleVehiclesClassesSlugRoute =
  LocaleVehiclesClassesSlugRouteImport.update({
    id: '/vehicles/classes/$slug',
    path: '/vehicles/classes/$slug',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProviderInviteTokenRoute =
  LocaleProviderInviteTokenRouteImport.update({
    id: '/provider/invite/$token',
    path: '/provider/invite/$token',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleManageOperatorSlugDashboardRoute =
  LocaleManageOperatorSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LocaleManageOperatorSlugRoute,
  } as any)
const LocaleRenterBookingsNewRoute = LocaleRenterBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleRenterBookingsRoute,
} as any)
const LocaleRenterBookingsConfirmationRoute =
  LocaleRenterBookingsConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => LocaleRenterBookingsRoute,
  } as any)
const LocaleBusinessManageBookingsRoute =
  LocaleBusinessManageBookingsRouteImport.update({
    id: '/manage/bookings',
    path: '/manage/bookings',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/bookings': typeof LocaleRenterBookingsRouteWithChildren
  '/$locale/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/manage/$operatorSlug': typeof LocaleManageOperatorSlugRouteWithChildren
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/manage/bookings': typeof LocaleBusinessManageBookingsRoute
  '/$locale/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/manage/$operatorSlug/dashboard': typeof LocaleManageOperatorSlugDashboardRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/bookings/': typeof LocaleRenterBookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/manage/$operatorSlug': typeof LocaleManageOperatorSlugRouteWithChildren
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles': typeof LocaleVehiclesIndexRoute
  '/$locale/manage/bookings': typeof LocaleBusinessManageBookingsRoute
  '/$locale/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/manage/$operatorSlug/dashboard': typeof LocaleManageOperatorSlugDashboardRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/bookings': typeof LocaleRenterBookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_business': typeof LocaleBusinessRouteWithChildren
  '/$locale/_renter': typeof LocaleRenterRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_business/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/_renter/bookings': typeof LocaleRenterBookingsRouteWithChildren
  '/$locale/_renter/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/manage/$operatorSlug': typeof LocaleManageOperatorSlugRouteWithChildren
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/_business/manage/bookings': typeof LocaleBusinessManageBookingsRoute
  '/$locale/_renter/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/_renter/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/manage/$operatorSlug/dashboard': typeof LocaleManageOperatorSlugDashboardRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/_renter/bookings/': typeof LocaleRenterBookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/dashboard'
    | '/$locale/bookings'
    | '/$locale/documents'
    | '/$locale/manage/$operatorSlug'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles/'
    | '/$locale/manage/bookings'
    | '/$locale/bookings/confirmation'
    | '/$locale/bookings/new'
    | '/$locale/manage/$operatorSlug/dashboard'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/dashboard'
    | '/$locale/documents'
    | '/$locale/manage/$operatorSlug'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles'
    | '/$locale/manage/bookings'
    | '/$locale/bookings/confirmation'
    | '/$locale/bookings/new'
    | '/$locale/manage/$operatorSlug/dashboard'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/bookings'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_business'
    | '/$locale/_renter'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/_business/dashboard'
    | '/$locale/_renter/bookings'
    | '/$locale/_renter/documents'
    | '/$locale/manage/$operatorSlug'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles/'
    | '/$locale/_business/manage/bookings'
    | '/$locale/_renter/bookings/confirmation'
    | '/$locale/_renter/bookings/new'
    | '/$locale/manage/$operatorSlug/dashboard'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/_renter/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ProviderInviteTokenRoute: typeof ProviderInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter': {
      id: '/$locale/_renter'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRenterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_business': {
      id: '/$locale/_business'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleBusinessRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/vehicles/': {
      id: '/$locale/vehicles/'
      path: '/vehicles'
      fullPath: '/$locale/vehicles/'
      preLoaderRoute: typeof LocaleVehiclesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/provider/invite/$token': {
      id: '/provider/invite/$token'
      path: '/provider/invite/$token'
      fullPath: '/provider/invite/$token'
      preLoaderRoute: typeof ProviderInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/storefronts/$locationId': {
      id: '/$locale/storefronts/$locationId'
      path: '/storefronts/$locationId'
      fullPath: '/$locale/storefronts/$locationId'
      preLoaderRoute: typeof LocaleStorefrontsLocationIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/provider/login': {
      id: '/$locale/provider/login'
      path: '/provider/login'
      fullPath: '/$locale/provider/login'
      preLoaderRoute: typeof LocaleProviderLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/manage/$operatorSlug': {
      id: '/$locale/manage/$operatorSlug'
      path: '/manage/$operatorSlug'
      fullPath: '/$locale/manage/$operatorSlug'
      preLoaderRoute: typeof LocaleManageOperatorSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter/documents': {
      id: '/$locale/_renter/documents'
      path: '/documents'
      fullPath: '/$locale/documents'
      preLoaderRoute: typeof LocaleRenterDocumentsRouteImport
      parentRoute: typeof LocaleRenterRoute
    }
    '/$locale/_renter/bookings': {
      id: '/$locale/_renter/bookings'
      path: '/bookings'
      fullPath: '/$locale/bookings'
      preLoaderRoute: typeof LocaleRenterBookingsRouteImport
      parentRoute: typeof LocaleRenterRoute
    }
    '/$locale/_business/dashboard': {
      id: '/$locale/_business/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleBusinessDashboardRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_renter/bookings/': {
      id: '/$locale/_renter/bookings/'
      path: '/'
      fullPath: '/$locale/bookings/'
      preLoaderRoute: typeof LocaleRenterBookingsIndexRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/vehicles/classes/$slug': {
      id: '/$locale/vehicles/classes/$slug'
      path: '/vehicles/classes/$slug'
      fullPath: '/$locale/vehicles/classes/$slug'
      preLoaderRoute: typeof LocaleVehiclesClassesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/provider/invite/$token': {
      id: '/$locale/provider/invite/$token'
      path: '/provider/invite/$token'
      fullPath: '/$locale/provider/invite/$token'
      preLoaderRoute: typeof LocaleProviderInviteTokenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/manage/$operatorSlug/dashboard': {
      id: '/$locale/manage/$operatorSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/manage/$operatorSlug/dashboard'
      preLoaderRoute: typeof LocaleManageOperatorSlugDashboardRouteImport
      parentRoute: typeof LocaleManageOperatorSlugRoute
    }
    '/$locale/_renter/bookings/new': {
      id: '/$locale/_renter/bookings/new'
      path: '/new'
      fullPath: '/$locale/bookings/new'
      preLoaderRoute: typeof LocaleRenterBookingsNewRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/_renter/bookings/confirmation': {
      id: '/$locale/_renter/bookings/confirmation'
      path: '/confirmation'
      fullPath: '/$locale/bookings/confirmation'
      preLoaderRoute: typeof LocaleRenterBookingsConfirmationRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/_business/manage/bookings': {
      id: '/$locale/_business/manage/bookings'
      path: '/manage/bookings'
      fullPath: '/$locale/manage/bookings'
      preLoaderRoute: typeof LocaleBusinessManageBookingsRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
  }
}

interface LocaleBusinessRouteChildren {
  LocaleBusinessDashboardRoute: typeof LocaleBusinessDashboardRoute
  LocaleBusinessManageBookingsRoute: typeof LocaleBusinessManageBookingsRoute
}

const LocaleBusinessRouteChildren: LocaleBusinessRouteChildren = {
  LocaleBusinessDashboardRoute: LocaleBusinessDashboardRoute,
  LocaleBusinessManageBookingsRoute: LocaleBusinessManageBookingsRoute,
}

const LocaleBusinessRouteWithChildren = LocaleBusinessRoute._addFileChildren(
  LocaleBusinessRouteChildren,
)

interface LocaleRenterBookingsRouteChildren {
  LocaleRenterBookingsConfirmationRoute: typeof LocaleRenterBookingsConfirmationRoute
  LocaleRenterBookingsNewRoute: typeof LocaleRenterBookingsNewRoute
  LocaleRenterBookingsIndexRoute: typeof LocaleRenterBookingsIndexRoute
}

const LocaleRenterBookingsRouteChildren: LocaleRenterBookingsRouteChildren = {
  LocaleRenterBookingsConfirmationRoute: LocaleRenterBookingsConfirmationRoute,
  LocaleRenterBookingsNewRoute: LocaleRenterBookingsNewRoute,
  LocaleRenterBookingsIndexRoute: LocaleRenterBookingsIndexRoute,
}

const LocaleRenterBookingsRouteWithChildren =
  LocaleRenterBookingsRoute._addFileChildren(LocaleRenterBookingsRouteChildren)

interface LocaleRenterRouteChildren {
  LocaleRenterBookingsRoute: typeof LocaleRenterBookingsRouteWithChildren
  LocaleRenterDocumentsRoute: typeof LocaleRenterDocumentsRoute
}

const LocaleRenterRouteChildren: LocaleRenterRouteChildren = {
  LocaleRenterBookingsRoute: LocaleRenterBookingsRouteWithChildren,
  LocaleRenterDocumentsRoute: LocaleRenterDocumentsRoute,
}

const LocaleRenterRouteWithChildren = LocaleRenterRoute._addFileChildren(
  LocaleRenterRouteChildren,
)

interface LocaleManageOperatorSlugRouteChildren {
  LocaleManageOperatorSlugDashboardRoute: typeof LocaleManageOperatorSlugDashboardRoute
}

const LocaleManageOperatorSlugRouteChildren: LocaleManageOperatorSlugRouteChildren =
  {
    LocaleManageOperatorSlugDashboardRoute:
      LocaleManageOperatorSlugDashboardRoute,
  }

const LocaleManageOperatorSlugRouteWithChildren =
  LocaleManageOperatorSlugRoute._addFileChildren(
    LocaleManageOperatorSlugRouteChildren,
  )

interface LocaleRouteChildren {
  LocaleBusinessRoute: typeof LocaleBusinessRouteWithChildren
  LocaleRenterRoute: typeof LocaleRenterRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleManageOperatorSlugRoute: typeof LocaleManageOperatorSlugRouteWithChildren
  LocaleProviderLoginRoute: typeof LocaleProviderLoginRoute
  LocaleStorefrontsLocationIdRoute: typeof LocaleStorefrontsLocationIdRoute
  LocaleVehiclesIndexRoute: typeof LocaleVehiclesIndexRoute
  LocaleProviderInviteTokenRoute: typeof LocaleProviderInviteTokenRoute
  LocaleVehiclesClassesSlugRoute: typeof LocaleVehiclesClassesSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBusinessRoute: LocaleBusinessRouteWithChildren,
  LocaleRenterRoute: LocaleRenterRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleManageOperatorSlugRoute: LocaleManageOperatorSlugRouteWithChildren,
  LocaleProviderLoginRoute: LocaleProviderLoginRoute,
  LocaleStorefrontsLocationIdRoute: LocaleStorefrontsLocationIdRoute,
  LocaleVehiclesIndexRoute: LocaleVehiclesIndexRoute,
  LocaleProviderInviteTokenRoute: LocaleProviderInviteTokenRoute,
  LocaleVehiclesClassesSlugRoute: LocaleVehiclesClassesSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ProviderInviteTokenRoute: ProviderInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
