/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSearchRouteImport } from './routes/$locale/search'
import { Route as LocaleLoginRouteImport } from './routes/$locale/login'
import { Route as LocaleRenterRouteImport } from './routes/$locale/_renter'
import { Route as LocaleBusinessRouteImport } from './routes/$locale/_business'
import { Route as LocaleAdminRouteImport } from './routes/$locale/_admin'
import { Route as LocaleVehiclesIndexRouteImport } from './routes/$locale/vehicles/index'
import { Route as ProviderInviteTokenRouteImport } from './routes/provider/invite/$token'
import { Route as LocaleStorefrontsLocationIdRouteImport } from './routes/$locale/storefronts/$locationId'
import { Route as LocaleProviderLoginRouteImport } from './routes/$locale/provider/login'
import { Route as LocaleRenterDocumentsRouteImport } from './routes/$locale/_renter/documents'
import { Route as LocaleRenterBookingsRouteImport } from './routes/$locale/_renter/bookings'
import { Route as LocaleBusinessDashboardRouteImport } from './routes/$locale/_business/dashboard'
import { Route as LocaleRenterBookingsIndexRouteImport } from './routes/$locale/_renter/bookings/index'
import { Route as LocaleAdminAdminIndexRouteImport } from './routes/$locale/_admin/admin/index'
import { Route as LocaleVehiclesClassesSlugRouteImport } from './routes/$locale/vehicles/classes/$slug'
import { Route as LocaleProviderInviteTokenRouteImport } from './routes/$locale/provider/invite/$token'
import { Route as LocaleRenterBookingsNewRouteImport } from './routes/$locale/_renter/bookings/new'
import { Route as LocaleRenterBookingsConfirmationRouteImport } from './routes/$locale/_renter/bookings/confirmation'
import { Route as LocaleBusinessManageTeamRouteImport } from './routes/$locale/_business/manage/team'
import { Route as LocaleBusinessManageSettingsRouteImport } from './routes/$locale/_business/manage/settings'
import { Route as LocaleBusinessManageLocationsRouteImport } from './routes/$locale/_business/manage/locations'
import { Route as LocaleBusinessManageInsuranceRouteImport } from './routes/$locale/_business/manage/insurance'
import { Route as LocaleBusinessManageFeesRouteImport } from './routes/$locale/_business/manage/fees'
import { Route as LocaleBusinessManageClassesRouteImport } from './routes/$locale/_business/manage/classes'
import { Route as LocaleBusinessManageAddOnsRouteImport } from './routes/$locale/_business/manage/add-ons'
import { Route as LocaleAdminAdminRevenueRouteImport } from './routes/$locale/_admin/admin/revenue'
import { Route as LocaleBusinessManageFleetIndexRouteImport } from './routes/$locale/_business/manage/fleet/index'
import { Route as LocaleBusinessManageBookingsIndexRouteImport } from './routes/$locale/_business/manage/bookings/index'
import { Route as LocaleBusinessManageFleetVehicleIdRouteImport } from './routes/$locale/_business/manage/fleet/$vehicleId'
import { Route as LocaleBusinessManageBookingsBookingIdRouteImport } from './routes/$locale/_business/manage/bookings/$bookingId'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSearchRoute = LocaleSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLoginRoute = LocaleLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRenterRoute = LocaleRenterRouteImport.update({
  id: '/_renter',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBusinessRoute = LocaleBusinessRouteImport.update({
  id: '/_business',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleAdminRoute = LocaleAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleVehiclesIndexRoute = LocaleVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => LocaleRoute,
} as any)
const ProviderInviteTokenRoute = ProviderInviteTokenRouteImport.update({
  id: '/provider/invite/$token',
  path: '/provider/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleStorefrontsLocationIdRoute =
  LocaleStorefrontsLocationIdRouteImport.update({
    id: '/storefronts/$locationId',
    path: '/storefronts/$locationId',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProviderLoginRoute = LocaleProviderLoginRouteImport.update({
  id: '/provider/login',
  path: '/provider/login',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleRenterDocumentsRoute = LocaleRenterDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => LocaleRenterRoute,
} as any)
const LocaleRenterBookingsRoute = LocaleRenterBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => LocaleRenterRoute,
} as any)
const LocaleBusinessDashboardRoute = LocaleBusinessDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleBusinessRoute,
} as any)
const LocaleRenterBookingsIndexRoute =
  LocaleRenterBookingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleRenterBookingsRoute,
  } as any)
const LocaleAdminAdminIndexRoute = LocaleAdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleVehiclesClassesSlugRoute =
  LocaleVehiclesClassesSlugRouteImport.update({
    id: '/vehicles/classes/$slug',
    path: '/vehicles/classes/$slug',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleProviderInviteTokenRoute =
  LocaleProviderInviteTokenRouteImport.update({
    id: '/provider/invite/$token',
    path: '/provider/invite/$token',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleRenterBookingsNewRoute = LocaleRenterBookingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LocaleRenterBookingsRoute,
} as any)
const LocaleRenterBookingsConfirmationRoute =
  LocaleRenterBookingsConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => LocaleRenterBookingsRoute,
  } as any)
const LocaleBusinessManageTeamRoute =
  LocaleBusinessManageTeamRouteImport.update({
    id: '/manage/team',
    path: '/manage/team',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageSettingsRoute =
  LocaleBusinessManageSettingsRouteImport.update({
    id: '/manage/settings',
    path: '/manage/settings',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageLocationsRoute =
  LocaleBusinessManageLocationsRouteImport.update({
    id: '/manage/locations',
    path: '/manage/locations',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageInsuranceRoute =
  LocaleBusinessManageInsuranceRouteImport.update({
    id: '/manage/insurance',
    path: '/manage/insurance',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageFeesRoute =
  LocaleBusinessManageFeesRouteImport.update({
    id: '/manage/fees',
    path: '/manage/fees',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageClassesRoute =
  LocaleBusinessManageClassesRouteImport.update({
    id: '/manage/classes',
    path: '/manage/classes',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageAddOnsRoute =
  LocaleBusinessManageAddOnsRouteImport.update({
    id: '/manage/add-ons',
    path: '/manage/add-ons',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleAdminAdminRevenueRoute = LocaleAdminAdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => LocaleAdminRoute,
} as any)
const LocaleBusinessManageFleetIndexRoute =
  LocaleBusinessManageFleetIndexRouteImport.update({
    id: '/manage/fleet/',
    path: '/manage/fleet/',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageBookingsIndexRoute =
  LocaleBusinessManageBookingsIndexRouteImport.update({
    id: '/manage/bookings/',
    path: '/manage/bookings/',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageFleetVehicleIdRoute =
  LocaleBusinessManageFleetVehicleIdRouteImport.update({
    id: '/manage/fleet/$vehicleId',
    path: '/manage/fleet/$vehicleId',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)
const LocaleBusinessManageBookingsBookingIdRoute =
  LocaleBusinessManageBookingsBookingIdRouteImport.update({
    id: '/manage/bookings/$bookingId',
    path: '/manage/bookings/$bookingId',
    getParentRoute: () => LocaleBusinessRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/bookings': typeof LocaleRenterBookingsRouteWithChildren
  '/$locale/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/admin/revenue': typeof LocaleAdminAdminRevenueRoute
  '/$locale/manage/add-ons': typeof LocaleBusinessManageAddOnsRoute
  '/$locale/manage/classes': typeof LocaleBusinessManageClassesRoute
  '/$locale/manage/fees': typeof LocaleBusinessManageFeesRoute
  '/$locale/manage/insurance': typeof LocaleBusinessManageInsuranceRoute
  '/$locale/manage/locations': typeof LocaleBusinessManageLocationsRoute
  '/$locale/manage/settings': typeof LocaleBusinessManageSettingsRoute
  '/$locale/manage/team': typeof LocaleBusinessManageTeamRoute
  '/$locale/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/admin/': typeof LocaleAdminAdminIndexRoute
  '/$locale/bookings/': typeof LocaleRenterBookingsIndexRoute
  '/$locale/manage/bookings/$bookingId': typeof LocaleBusinessManageBookingsBookingIdRoute
  '/$locale/manage/fleet/$vehicleId': typeof LocaleBusinessManageFleetVehicleIdRoute
  '/$locale/manage/bookings/': typeof LocaleBusinessManageBookingsIndexRoute
  '/$locale/manage/fleet/': typeof LocaleBusinessManageFleetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles': typeof LocaleVehiclesIndexRoute
  '/$locale/admin/revenue': typeof LocaleAdminAdminRevenueRoute
  '/$locale/manage/add-ons': typeof LocaleBusinessManageAddOnsRoute
  '/$locale/manage/classes': typeof LocaleBusinessManageClassesRoute
  '/$locale/manage/fees': typeof LocaleBusinessManageFeesRoute
  '/$locale/manage/insurance': typeof LocaleBusinessManageInsuranceRoute
  '/$locale/manage/locations': typeof LocaleBusinessManageLocationsRoute
  '/$locale/manage/settings': typeof LocaleBusinessManageSettingsRoute
  '/$locale/manage/team': typeof LocaleBusinessManageTeamRoute
  '/$locale/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/admin': typeof LocaleAdminAdminIndexRoute
  '/$locale/bookings': typeof LocaleRenterBookingsIndexRoute
  '/$locale/manage/bookings/$bookingId': typeof LocaleBusinessManageBookingsBookingIdRoute
  '/$locale/manage/fleet/$vehicleId': typeof LocaleBusinessManageFleetVehicleIdRoute
  '/$locale/manage/bookings': typeof LocaleBusinessManageBookingsIndexRoute
  '/$locale/manage/fleet': typeof LocaleBusinessManageFleetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/_admin': typeof LocaleAdminRouteWithChildren
  '/$locale/_business': typeof LocaleBusinessRouteWithChildren
  '/$locale/_renter': typeof LocaleRenterRouteWithChildren
  '/$locale/login': typeof LocaleLoginRoute
  '/$locale/search': typeof LocaleSearchRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/_business/dashboard': typeof LocaleBusinessDashboardRoute
  '/$locale/_renter/bookings': typeof LocaleRenterBookingsRouteWithChildren
  '/$locale/_renter/documents': typeof LocaleRenterDocumentsRoute
  '/$locale/provider/login': typeof LocaleProviderLoginRoute
  '/$locale/storefronts/$locationId': typeof LocaleStorefrontsLocationIdRoute
  '/provider/invite/$token': typeof ProviderInviteTokenRoute
  '/$locale/vehicles/': typeof LocaleVehiclesIndexRoute
  '/$locale/_admin/admin/revenue': typeof LocaleAdminAdminRevenueRoute
  '/$locale/_business/manage/add-ons': typeof LocaleBusinessManageAddOnsRoute
  '/$locale/_business/manage/classes': typeof LocaleBusinessManageClassesRoute
  '/$locale/_business/manage/fees': typeof LocaleBusinessManageFeesRoute
  '/$locale/_business/manage/insurance': typeof LocaleBusinessManageInsuranceRoute
  '/$locale/_business/manage/locations': typeof LocaleBusinessManageLocationsRoute
  '/$locale/_business/manage/settings': typeof LocaleBusinessManageSettingsRoute
  '/$locale/_business/manage/team': typeof LocaleBusinessManageTeamRoute
  '/$locale/_renter/bookings/confirmation': typeof LocaleRenterBookingsConfirmationRoute
  '/$locale/_renter/bookings/new': typeof LocaleRenterBookingsNewRoute
  '/$locale/provider/invite/$token': typeof LocaleProviderInviteTokenRoute
  '/$locale/vehicles/classes/$slug': typeof LocaleVehiclesClassesSlugRoute
  '/$locale/_admin/admin/': typeof LocaleAdminAdminIndexRoute
  '/$locale/_renter/bookings/': typeof LocaleRenterBookingsIndexRoute
  '/$locale/_business/manage/bookings/$bookingId': typeof LocaleBusinessManageBookingsBookingIdRoute
  '/$locale/_business/manage/fleet/$vehicleId': typeof LocaleBusinessManageFleetVehicleIdRoute
  '/$locale/_business/manage/bookings/': typeof LocaleBusinessManageBookingsIndexRoute
  '/$locale/_business/manage/fleet/': typeof LocaleBusinessManageFleetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/dashboard'
    | '/$locale/bookings'
    | '/$locale/documents'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles/'
    | '/$locale/admin/revenue'
    | '/$locale/manage/add-ons'
    | '/$locale/manage/classes'
    | '/$locale/manage/fees'
    | '/$locale/manage/insurance'
    | '/$locale/manage/locations'
    | '/$locale/manage/settings'
    | '/$locale/manage/team'
    | '/$locale/bookings/confirmation'
    | '/$locale/bookings/new'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/admin/'
    | '/$locale/bookings/'
    | '/$locale/manage/bookings/$bookingId'
    | '/$locale/manage/fleet/$vehicleId'
    | '/$locale/manage/bookings/'
    | '/$locale/manage/fleet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/dashboard'
    | '/$locale/documents'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles'
    | '/$locale/admin/revenue'
    | '/$locale/manage/add-ons'
    | '/$locale/manage/classes'
    | '/$locale/manage/fees'
    | '/$locale/manage/insurance'
    | '/$locale/manage/locations'
    | '/$locale/manage/settings'
    | '/$locale/manage/team'
    | '/$locale/bookings/confirmation'
    | '/$locale/bookings/new'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/admin'
    | '/$locale/bookings'
    | '/$locale/manage/bookings/$bookingId'
    | '/$locale/manage/fleet/$vehicleId'
    | '/$locale/manage/bookings'
    | '/$locale/manage/fleet'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/_admin'
    | '/$locale/_business'
    | '/$locale/_renter'
    | '/$locale/login'
    | '/$locale/search'
    | '/$locale/'
    | '/$locale/_business/dashboard'
    | '/$locale/_renter/bookings'
    | '/$locale/_renter/documents'
    | '/$locale/provider/login'
    | '/$locale/storefronts/$locationId'
    | '/provider/invite/$token'
    | '/$locale/vehicles/'
    | '/$locale/_admin/admin/revenue'
    | '/$locale/_business/manage/add-ons'
    | '/$locale/_business/manage/classes'
    | '/$locale/_business/manage/fees'
    | '/$locale/_business/manage/insurance'
    | '/$locale/_business/manage/locations'
    | '/$locale/_business/manage/settings'
    | '/$locale/_business/manage/team'
    | '/$locale/_renter/bookings/confirmation'
    | '/$locale/_renter/bookings/new'
    | '/$locale/provider/invite/$token'
    | '/$locale/vehicles/classes/$slug'
    | '/$locale/_admin/admin/'
    | '/$locale/_renter/bookings/'
    | '/$locale/_business/manage/bookings/$bookingId'
    | '/$locale/_business/manage/fleet/$vehicleId'
    | '/$locale/_business/manage/bookings/'
    | '/$locale/_business/manage/fleet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  ProviderInviteTokenRoute: typeof ProviderInviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/search': {
      id: '/$locale/search'
      path: '/search'
      fullPath: '/$locale/search'
      preLoaderRoute: typeof LocaleSearchRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/login': {
      id: '/$locale/login'
      path: '/login'
      fullPath: '/$locale/login'
      preLoaderRoute: typeof LocaleLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter': {
      id: '/$locale/_renter'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRenterRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_business': {
      id: '/$locale/_business'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleBusinessRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_admin': {
      id: '/$locale/_admin'
      path: ''
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleAdminRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/vehicles/': {
      id: '/$locale/vehicles/'
      path: '/vehicles'
      fullPath: '/$locale/vehicles/'
      preLoaderRoute: typeof LocaleVehiclesIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/provider/invite/$token': {
      id: '/provider/invite/$token'
      path: '/provider/invite/$token'
      fullPath: '/provider/invite/$token'
      preLoaderRoute: typeof ProviderInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/storefronts/$locationId': {
      id: '/$locale/storefronts/$locationId'
      path: '/storefronts/$locationId'
      fullPath: '/$locale/storefronts/$locationId'
      preLoaderRoute: typeof LocaleStorefrontsLocationIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/provider/login': {
      id: '/$locale/provider/login'
      path: '/provider/login'
      fullPath: '/$locale/provider/login'
      preLoaderRoute: typeof LocaleProviderLoginRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter/documents': {
      id: '/$locale/_renter/documents'
      path: '/documents'
      fullPath: '/$locale/documents'
      preLoaderRoute: typeof LocaleRenterDocumentsRouteImport
      parentRoute: typeof LocaleRenterRoute
    }
    '/$locale/_renter/bookings': {
      id: '/$locale/_renter/bookings'
      path: '/bookings'
      fullPath: '/$locale/bookings'
      preLoaderRoute: typeof LocaleRenterBookingsRouteImport
      parentRoute: typeof LocaleRenterRoute
    }
    '/$locale/_business/dashboard': {
      id: '/$locale/_business/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleBusinessDashboardRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_renter/bookings/': {
      id: '/$locale/_renter/bookings/'
      path: '/'
      fullPath: '/$locale/bookings/'
      preLoaderRoute: typeof LocaleRenterBookingsIndexRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/_admin/admin/': {
      id: '/$locale/_admin/admin/'
      path: '/admin'
      fullPath: '/$locale/admin/'
      preLoaderRoute: typeof LocaleAdminAdminIndexRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/vehicles/classes/$slug': {
      id: '/$locale/vehicles/classes/$slug'
      path: '/vehicles/classes/$slug'
      fullPath: '/$locale/vehicles/classes/$slug'
      preLoaderRoute: typeof LocaleVehiclesClassesSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/provider/invite/$token': {
      id: '/$locale/provider/invite/$token'
      path: '/provider/invite/$token'
      fullPath: '/$locale/provider/invite/$token'
      preLoaderRoute: typeof LocaleProviderInviteTokenRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/_renter/bookings/new': {
      id: '/$locale/_renter/bookings/new'
      path: '/new'
      fullPath: '/$locale/bookings/new'
      preLoaderRoute: typeof LocaleRenterBookingsNewRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/_renter/bookings/confirmation': {
      id: '/$locale/_renter/bookings/confirmation'
      path: '/confirmation'
      fullPath: '/$locale/bookings/confirmation'
      preLoaderRoute: typeof LocaleRenterBookingsConfirmationRouteImport
      parentRoute: typeof LocaleRenterBookingsRoute
    }
    '/$locale/_business/manage/team': {
      id: '/$locale/_business/manage/team'
      path: '/manage/team'
      fullPath: '/$locale/manage/team'
      preLoaderRoute: typeof LocaleBusinessManageTeamRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/settings': {
      id: '/$locale/_business/manage/settings'
      path: '/manage/settings'
      fullPath: '/$locale/manage/settings'
      preLoaderRoute: typeof LocaleBusinessManageSettingsRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/locations': {
      id: '/$locale/_business/manage/locations'
      path: '/manage/locations'
      fullPath: '/$locale/manage/locations'
      preLoaderRoute: typeof LocaleBusinessManageLocationsRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/insurance': {
      id: '/$locale/_business/manage/insurance'
      path: '/manage/insurance'
      fullPath: '/$locale/manage/insurance'
      preLoaderRoute: typeof LocaleBusinessManageInsuranceRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/fees': {
      id: '/$locale/_business/manage/fees'
      path: '/manage/fees'
      fullPath: '/$locale/manage/fees'
      preLoaderRoute: typeof LocaleBusinessManageFeesRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/classes': {
      id: '/$locale/_business/manage/classes'
      path: '/manage/classes'
      fullPath: '/$locale/manage/classes'
      preLoaderRoute: typeof LocaleBusinessManageClassesRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/add-ons': {
      id: '/$locale/_business/manage/add-ons'
      path: '/manage/add-ons'
      fullPath: '/$locale/manage/add-ons'
      preLoaderRoute: typeof LocaleBusinessManageAddOnsRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_admin/admin/revenue': {
      id: '/$locale/_admin/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/$locale/admin/revenue'
      preLoaderRoute: typeof LocaleAdminAdminRevenueRouteImport
      parentRoute: typeof LocaleAdminRoute
    }
    '/$locale/_business/manage/fleet/': {
      id: '/$locale/_business/manage/fleet/'
      path: '/manage/fleet'
      fullPath: '/$locale/manage/fleet/'
      preLoaderRoute: typeof LocaleBusinessManageFleetIndexRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/bookings/': {
      id: '/$locale/_business/manage/bookings/'
      path: '/manage/bookings'
      fullPath: '/$locale/manage/bookings/'
      preLoaderRoute: typeof LocaleBusinessManageBookingsIndexRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/fleet/$vehicleId': {
      id: '/$locale/_business/manage/fleet/$vehicleId'
      path: '/manage/fleet/$vehicleId'
      fullPath: '/$locale/manage/fleet/$vehicleId'
      preLoaderRoute: typeof LocaleBusinessManageFleetVehicleIdRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
    '/$locale/_business/manage/bookings/$bookingId': {
      id: '/$locale/_business/manage/bookings/$bookingId'
      path: '/manage/bookings/$bookingId'
      fullPath: '/$locale/manage/bookings/$bookingId'
      preLoaderRoute: typeof LocaleBusinessManageBookingsBookingIdRouteImport
      parentRoute: typeof LocaleBusinessRoute
    }
  }
}

interface LocaleAdminRouteChildren {
  LocaleAdminAdminRevenueRoute: typeof LocaleAdminAdminRevenueRoute
  LocaleAdminAdminIndexRoute: typeof LocaleAdminAdminIndexRoute
}

const LocaleAdminRouteChildren: LocaleAdminRouteChildren = {
  LocaleAdminAdminRevenueRoute: LocaleAdminAdminRevenueRoute,
  LocaleAdminAdminIndexRoute: LocaleAdminAdminIndexRoute,
}

const LocaleAdminRouteWithChildren = LocaleAdminRoute._addFileChildren(
  LocaleAdminRouteChildren,
)

interface LocaleBusinessRouteChildren {
  LocaleBusinessDashboardRoute: typeof LocaleBusinessDashboardRoute
  LocaleBusinessManageAddOnsRoute: typeof LocaleBusinessManageAddOnsRoute
  LocaleBusinessManageClassesRoute: typeof LocaleBusinessManageClassesRoute
  LocaleBusinessManageFeesRoute: typeof LocaleBusinessManageFeesRoute
  LocaleBusinessManageInsuranceRoute: typeof LocaleBusinessManageInsuranceRoute
  LocaleBusinessManageLocationsRoute: typeof LocaleBusinessManageLocationsRoute
  LocaleBusinessManageSettingsRoute: typeof LocaleBusinessManageSettingsRoute
  LocaleBusinessManageTeamRoute: typeof LocaleBusinessManageTeamRoute
  LocaleBusinessManageBookingsBookingIdRoute: typeof LocaleBusinessManageBookingsBookingIdRoute
  LocaleBusinessManageFleetVehicleIdRoute: typeof LocaleBusinessManageFleetVehicleIdRoute
  LocaleBusinessManageBookingsIndexRoute: typeof LocaleBusinessManageBookingsIndexRoute
  LocaleBusinessManageFleetIndexRoute: typeof LocaleBusinessManageFleetIndexRoute
}

const LocaleBusinessRouteChildren: LocaleBusinessRouteChildren = {
  LocaleBusinessDashboardRoute: LocaleBusinessDashboardRoute,
  LocaleBusinessManageAddOnsRoute: LocaleBusinessManageAddOnsRoute,
  LocaleBusinessManageClassesRoute: LocaleBusinessManageClassesRoute,
  LocaleBusinessManageFeesRoute: LocaleBusinessManageFeesRoute,
  LocaleBusinessManageInsuranceRoute: LocaleBusinessManageInsuranceRoute,
  LocaleBusinessManageLocationsRoute: LocaleBusinessManageLocationsRoute,
  LocaleBusinessManageSettingsRoute: LocaleBusinessManageSettingsRoute,
  LocaleBusinessManageTeamRoute: LocaleBusinessManageTeamRoute,
  LocaleBusinessManageBookingsBookingIdRoute:
    LocaleBusinessManageBookingsBookingIdRoute,
  LocaleBusinessManageFleetVehicleIdRoute:
    LocaleBusinessManageFleetVehicleIdRoute,
  LocaleBusinessManageBookingsIndexRoute:
    LocaleBusinessManageBookingsIndexRoute,
  LocaleBusinessManageFleetIndexRoute: LocaleBusinessManageFleetIndexRoute,
}

const LocaleBusinessRouteWithChildren = LocaleBusinessRoute._addFileChildren(
  LocaleBusinessRouteChildren,
)

interface LocaleRenterBookingsRouteChildren {
  LocaleRenterBookingsConfirmationRoute: typeof LocaleRenterBookingsConfirmationRoute
  LocaleRenterBookingsNewRoute: typeof LocaleRenterBookingsNewRoute
  LocaleRenterBookingsIndexRoute: typeof LocaleRenterBookingsIndexRoute
}

const LocaleRenterBookingsRouteChildren: LocaleRenterBookingsRouteChildren = {
  LocaleRenterBookingsConfirmationRoute: LocaleRenterBookingsConfirmationRoute,
  LocaleRenterBookingsNewRoute: LocaleRenterBookingsNewRoute,
  LocaleRenterBookingsIndexRoute: LocaleRenterBookingsIndexRoute,
}

const LocaleRenterBookingsRouteWithChildren =
  LocaleRenterBookingsRoute._addFileChildren(LocaleRenterBookingsRouteChildren)

interface LocaleRenterRouteChildren {
  LocaleRenterBookingsRoute: typeof LocaleRenterBookingsRouteWithChildren
  LocaleRenterDocumentsRoute: typeof LocaleRenterDocumentsRoute
}

const LocaleRenterRouteChildren: LocaleRenterRouteChildren = {
  LocaleRenterBookingsRoute: LocaleRenterBookingsRouteWithChildren,
  LocaleRenterDocumentsRoute: LocaleRenterDocumentsRoute,
}

const LocaleRenterRouteWithChildren = LocaleRenterRoute._addFileChildren(
  LocaleRenterRouteChildren,
)

interface LocaleRouteChildren {
  LocaleAdminRoute: typeof LocaleAdminRouteWithChildren
  LocaleBusinessRoute: typeof LocaleBusinessRouteWithChildren
  LocaleRenterRoute: typeof LocaleRenterRouteWithChildren
  LocaleLoginRoute: typeof LocaleLoginRoute
  LocaleSearchRoute: typeof LocaleSearchRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleProviderLoginRoute: typeof LocaleProviderLoginRoute
  LocaleStorefrontsLocationIdRoute: typeof LocaleStorefrontsLocationIdRoute
  LocaleVehiclesIndexRoute: typeof LocaleVehiclesIndexRoute
  LocaleProviderInviteTokenRoute: typeof LocaleProviderInviteTokenRoute
  LocaleVehiclesClassesSlugRoute: typeof LocaleVehiclesClassesSlugRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleAdminRoute: LocaleAdminRouteWithChildren,
  LocaleBusinessRoute: LocaleBusinessRouteWithChildren,
  LocaleRenterRoute: LocaleRenterRouteWithChildren,
  LocaleLoginRoute: LocaleLoginRoute,
  LocaleSearchRoute: LocaleSearchRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleProviderLoginRoute: LocaleProviderLoginRoute,
  LocaleStorefrontsLocationIdRoute: LocaleStorefrontsLocationIdRoute,
  LocaleVehiclesIndexRoute: LocaleVehiclesIndexRoute,
  LocaleProviderInviteTokenRoute: LocaleProviderInviteTokenRoute,
  LocaleVehiclesClassesSlugRoute: LocaleVehiclesClassesSlugRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  ProviderInviteTokenRoute: ProviderInviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
