import type { DemoRegion } from './regions'

/**
 * #1276 nationwide region expansion — west Japan (Mie -> Okinawa, excl. the Kansai demo core) (JIS X 0401 24-47). Split out of
 * regions.ts to stay under the 800-line file-size cap; concatenated after the
 * Kansai core in DEMO_REGIONS. Pure static reference data (adjacency list):
 * PREFECTURE roots (parentId null, navigation-only) each followed by their
 * assignable CITY children so the self-FK resolves on insert.
 */
export const WEST_JAPAN_REGIONS: readonly DemoRegion[] = [
  // ── Mie 三重県 ────────────────────────────────────────────────────────────────
  {
    id: 'reg_mie',
    parentId: null,
    nameEn: 'Mie',
    nameJa: '三重県',
    nameZh: '三重县',
    sortOrder: 24,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'mie',
  },
  {
    id: 'reg_tsu_city',
    parentId: 'reg_mie',
    nameEn: 'Tsu',
    nameJa: '津市',
    nameZh: '津市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'tsu-city',
  },
  // ── Shiga 滋賀県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_shiga',
    parentId: null,
    nameEn: 'Shiga',
    nameJa: '滋賀県',
    nameZh: '滋贺县',
    sortOrder: 25,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'shiga',
  },
  {
    id: 'reg_otsu_city',
    parentId: 'reg_shiga',
    nameEn: 'Otsu',
    nameJa: '大津市',
    nameZh: '大津市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'otsu-city',
  },
  // ── Wakayama 和歌山県 ─────────────────────────────────────────────────────────
  {
    id: 'reg_wakayama',
    parentId: null,
    nameEn: 'Wakayama',
    nameJa: '和歌山県',
    nameZh: '和歌山县',
    sortOrder: 30,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'wakayama',
  },
  {
    id: 'reg_wakayama_city',
    parentId: 'reg_wakayama',
    nameEn: 'Wakayama',
    nameJa: '和歌山市',
    nameZh: '和歌山市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'wakayama-city',
  },
  // ── Tottori 鳥取県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_tottori',
    parentId: null,
    nameEn: 'Tottori',
    nameJa: '鳥取県',
    nameZh: '鸟取县',
    sortOrder: 31,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'tottori',
  },
  {
    id: 'reg_tottori_city',
    parentId: 'reg_tottori',
    nameEn: 'Tottori',
    nameJa: '鳥取市',
    nameZh: '鸟取市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'tottori-city',
  },
  // ── Shimane 島根県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_shimane',
    parentId: null,
    nameEn: 'Shimane',
    nameJa: '島根県',
    nameZh: '岛根县',
    sortOrder: 32,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'shimane',
  },
  {
    id: 'reg_matsue_city',
    parentId: 'reg_shimane',
    nameEn: 'Matsue',
    nameJa: '松江市',
    nameZh: '松江市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'matsue-city',
  },
  // ── Okayama 岡山県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_okayama',
    parentId: null,
    nameEn: 'Okayama',
    nameJa: '岡山県',
    nameZh: '冈山县',
    sortOrder: 33,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'okayama',
  },
  {
    id: 'reg_okayama_city',
    parentId: 'reg_okayama',
    nameEn: 'Okayama',
    nameJa: '岡山市',
    nameZh: '冈山市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'okayama-city',
  },
  // ── Hiroshima 広島県 ──────────────────────────────────────────────────────────
  {
    id: 'reg_hiroshima',
    parentId: null,
    nameEn: 'Hiroshima',
    nameJa: '広島県',
    nameZh: '广岛县',
    sortOrder: 34,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'hiroshima',
  },
  {
    id: 'reg_hiroshima_city',
    parentId: 'reg_hiroshima',
    nameEn: 'Hiroshima',
    nameJa: '広島市',
    nameZh: '广岛市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'hiroshima-city',
  },
  // ── Yamaguchi 山口県 ──────────────────────────────────────────────────────────
  {
    id: 'reg_yamaguchi',
    parentId: null,
    nameEn: 'Yamaguchi',
    nameJa: '山口県',
    nameZh: '山口县',
    sortOrder: 35,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'yamaguchi',
  },
  {
    id: 'reg_yamaguchi_city',
    parentId: 'reg_yamaguchi',
    nameEn: 'Yamaguchi',
    nameJa: '山口市',
    nameZh: '山口市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'yamaguchi-city',
  },
  // ── Tokushima 徳島県 ──────────────────────────────────────────────────────────
  {
    id: 'reg_tokushima',
    parentId: null,
    nameEn: 'Tokushima',
    nameJa: '徳島県',
    nameZh: '德岛县',
    sortOrder: 36,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'tokushima',
  },
  {
    id: 'reg_tokushima_city',
    parentId: 'reg_tokushima',
    nameEn: 'Tokushima',
    nameJa: '徳島市',
    nameZh: '德岛市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'tokushima-city',
  },
  // ── Kagawa 香川県 ─────────────────────────────────────────────────────────────
  {
    id: 'reg_kagawa',
    parentId: null,
    nameEn: 'Kagawa',
    nameJa: '香川県',
    nameZh: '香川县',
    sortOrder: 37,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'kagawa',
  },
  {
    id: 'reg_takamatsu_city',
    parentId: 'reg_kagawa',
    nameEn: 'Takamatsu',
    nameJa: '高松市',
    nameZh: '高松市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'takamatsu-city',
  },
  // ── Ehime 愛媛県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_ehime',
    parentId: null,
    nameEn: 'Ehime',
    nameJa: '愛媛県',
    nameZh: '爱媛县',
    sortOrder: 38,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'ehime',
  },
  {
    id: 'reg_matsuyama_city',
    parentId: 'reg_ehime',
    nameEn: 'Matsuyama',
    nameJa: '松山市',
    nameZh: '松山市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'matsuyama-city',
  },
  // ── Kochi 高知県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_kochi',
    parentId: null,
    nameEn: 'Kochi',
    nameJa: '高知県',
    nameZh: '高知县',
    sortOrder: 39,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'kochi',
  },
  {
    id: 'reg_kochi_city',
    parentId: 'reg_kochi',
    nameEn: 'Kochi',
    nameJa: '高知市',
    nameZh: '高知市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kochi-city',
  },
  // ── Fukuoka 福岡県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_fukuoka',
    parentId: null,
    nameEn: 'Fukuoka',
    nameJa: '福岡県',
    nameZh: '福冈县',
    sortOrder: 40,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'fukuoka',
  },
  {
    id: 'reg_fukuoka_city',
    parentId: 'reg_fukuoka',
    nameEn: 'Fukuoka',
    nameJa: '福岡市',
    nameZh: '福冈市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'fukuoka-city',
  },
  {
    id: 'reg_kitakyushu_city',
    parentId: 'reg_fukuoka',
    nameEn: 'Kitakyushu',
    nameJa: '北九州市',
    nameZh: '北九州市',
    sortOrder: 2,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kitakyushu-city',
  },
  // ── Saga 佐賀県 ───────────────────────────────────────────────────────────────
  {
    id: 'reg_saga',
    parentId: null,
    nameEn: 'Saga',
    nameJa: '佐賀県',
    nameZh: '佐贺县',
    sortOrder: 41,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'saga',
  },
  {
    id: 'reg_saga_city',
    parentId: 'reg_saga',
    nameEn: 'Saga',
    nameJa: '佐賀市',
    nameZh: '佐贺市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'saga-city',
  },
  // ── Nagasaki 長崎県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_nagasaki',
    parentId: null,
    nameEn: 'Nagasaki',
    nameJa: '長崎県',
    nameZh: '长崎县',
    sortOrder: 42,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'nagasaki',
  },
  {
    id: 'reg_nagasaki_city',
    parentId: 'reg_nagasaki',
    nameEn: 'Nagasaki',
    nameJa: '長崎市',
    nameZh: '长崎市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'nagasaki-city',
  },
  // ── Kumamoto 熊本県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_kumamoto',
    parentId: null,
    nameEn: 'Kumamoto',
    nameJa: '熊本県',
    nameZh: '熊本县',
    sortOrder: 43,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'kumamoto',
  },
  {
    id: 'reg_kumamoto_city',
    parentId: 'reg_kumamoto',
    nameEn: 'Kumamoto',
    nameJa: '熊本市',
    nameZh: '熊本市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kumamoto-city',
  },
  // ── Oita 大分県 ───────────────────────────────────────────────────────────────
  {
    id: 'reg_oita',
    parentId: null,
    nameEn: 'Oita',
    nameJa: '大分県',
    nameZh: '大分县',
    sortOrder: 44,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'oita',
  },
  {
    id: 'reg_oita_city',
    parentId: 'reg_oita',
    nameEn: 'Oita',
    nameJa: '大分市',
    nameZh: '大分市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'oita-city',
  },
  // ── Miyazaki 宮崎県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_miyazaki',
    parentId: null,
    nameEn: 'Miyazaki',
    nameJa: '宮崎県',
    nameZh: '宫崎县',
    sortOrder: 45,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'miyazaki',
  },
  {
    id: 'reg_miyazaki_city',
    parentId: 'reg_miyazaki',
    nameEn: 'Miyazaki',
    nameJa: '宮崎市',
    nameZh: '宫崎市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'miyazaki-city',
  },
  // ── Kagoshima 鹿児島県 ────────────────────────────────────────────────────────
  {
    id: 'reg_kagoshima',
    parentId: null,
    nameEn: 'Kagoshima',
    nameJa: '鹿児島県',
    nameZh: '鹿儿岛县',
    sortOrder: 46,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'kagoshima',
  },
  {
    id: 'reg_kagoshima_city',
    parentId: 'reg_kagoshima',
    nameEn: 'Kagoshima',
    nameJa: '鹿児島市',
    nameZh: '鹿儿岛市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kagoshima-city',
  },
  // ── Okinawa 沖縄県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_okinawa',
    parentId: null,
    nameEn: 'Okinawa',
    nameJa: '沖縄県',
    nameZh: '冲绳县',
    sortOrder: 47,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'okinawa',
  },
  {
    id: 'reg_naha_city',
    parentId: 'reg_okinawa',
    nameEn: 'Naha',
    nameJa: '那覇市',
    nameZh: '那霸市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'naha-city',
  },
] as const
