import type { DemoRegion } from './regions'

/**
 * #1276 nationwide region expansion — east Japan (Hokkaido -> Aichi) (JIS X 0401 1-23). Split out of
 * regions.ts to stay under the 800-line file-size cap; concatenated after the
 * Kansai core in DEMO_REGIONS. Pure static reference data (adjacency list):
 * PREFECTURE roots (parentId null, navigation-only) each followed by their
 * assignable CITY children so the self-FK resolves on insert.
 */
export const EAST_JAPAN_REGIONS: readonly DemoRegion[] = [
  // ── Hokkaido 北海道 ───────────────────────────────────────────────────────────
  {
    id: 'reg_hokkaido',
    parentId: null,
    nameEn: 'Hokkaido',
    nameJa: '北海道',
    nameZh: '北海道',
    sortOrder: 1,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'hokkaido',
  },
  {
    id: 'reg_sapporo_city',
    parentId: 'reg_hokkaido',
    nameEn: 'Sapporo',
    nameJa: '札幌市',
    nameZh: '札幌市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'sapporo-city',
  },
  // ── Aomori 青森県 ─────────────────────────────────────────────────────────────
  {
    id: 'reg_aomori',
    parentId: null,
    nameEn: 'Aomori',
    nameJa: '青森県',
    nameZh: '青森县',
    sortOrder: 2,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'aomori',
  },
  {
    id: 'reg_aomori_city',
    parentId: 'reg_aomori',
    nameEn: 'Aomori',
    nameJa: '青森市',
    nameZh: '青森市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'aomori-city',
  },
  // ── Iwate 岩手県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_iwate',
    parentId: null,
    nameEn: 'Iwate',
    nameJa: '岩手県',
    nameZh: '岩手县',
    sortOrder: 3,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'iwate',
  },
  {
    id: 'reg_morioka_city',
    parentId: 'reg_iwate',
    nameEn: 'Morioka',
    nameJa: '盛岡市',
    nameZh: '盛冈市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'morioka-city',
  },
  // ── Miyagi 宮城県 ─────────────────────────────────────────────────────────────
  {
    id: 'reg_miyagi',
    parentId: null,
    nameEn: 'Miyagi',
    nameJa: '宮城県',
    nameZh: '宫城县',
    sortOrder: 4,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'miyagi',
  },
  {
    id: 'reg_sendai_city',
    parentId: 'reg_miyagi',
    nameEn: 'Sendai',
    nameJa: '仙台市',
    nameZh: '仙台市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'sendai-city',
  },
  // ── Akita 秋田県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_akita',
    parentId: null,
    nameEn: 'Akita',
    nameJa: '秋田県',
    nameZh: '秋田县',
    sortOrder: 5,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'akita',
  },
  {
    id: 'reg_akita_city',
    parentId: 'reg_akita',
    nameEn: 'Akita',
    nameJa: '秋田市',
    nameZh: '秋田市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'akita-city',
  },
  // ── Yamagata 山形県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_yamagata',
    parentId: null,
    nameEn: 'Yamagata',
    nameJa: '山形県',
    nameZh: '山形县',
    sortOrder: 6,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'yamagata',
  },
  {
    id: 'reg_yamagata_city',
    parentId: 'reg_yamagata',
    nameEn: 'Yamagata',
    nameJa: '山形市',
    nameZh: '山形市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'yamagata-city',
  },
  // ── Fukushima 福島県 ──────────────────────────────────────────────────────────
  {
    id: 'reg_fukushima',
    parentId: null,
    nameEn: 'Fukushima',
    nameJa: '福島県',
    nameZh: '福岛县',
    sortOrder: 7,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'fukushima',
  },
  {
    id: 'reg_fukushima_city',
    parentId: 'reg_fukushima',
    nameEn: 'Fukushima',
    nameJa: '福島市',
    nameZh: '福岛市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'fukushima-city',
  },
  // ── Ibaraki 茨城県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_ibaraki',
    parentId: null,
    nameEn: 'Ibaraki',
    nameJa: '茨城県',
    nameZh: '茨城县',
    sortOrder: 8,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'ibaraki',
  },
  {
    id: 'reg_mito_city',
    parentId: 'reg_ibaraki',
    nameEn: 'Mito',
    nameJa: '水戸市',
    nameZh: '水户市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'mito-city',
  },
  // ── Tochigi 栃木県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_tochigi',
    parentId: null,
    nameEn: 'Tochigi',
    nameJa: '栃木県',
    nameZh: '枥木县',
    sortOrder: 9,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'tochigi',
  },
  {
    id: 'reg_utsunomiya_city',
    parentId: 'reg_tochigi',
    nameEn: 'Utsunomiya',
    nameJa: '宇都宮市',
    nameZh: '宇都宫市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'utsunomiya-city',
  },
  // ── Gunma 群馬県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_gunma',
    parentId: null,
    nameEn: 'Gunma',
    nameJa: '群馬県',
    nameZh: '群马县',
    sortOrder: 10,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'gunma',
  },
  {
    id: 'reg_maebashi_city',
    parentId: 'reg_gunma',
    nameEn: 'Maebashi',
    nameJa: '前橋市',
    nameZh: '前桥市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'maebashi-city',
  },
  // ── Saitama 埼玉県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_saitama',
    parentId: null,
    nameEn: 'Saitama',
    nameJa: '埼玉県',
    nameZh: '埼玉县',
    sortOrder: 11,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'saitama',
  },
  {
    id: 'reg_saitama_city',
    parentId: 'reg_saitama',
    nameEn: 'Saitama',
    nameJa: 'さいたま市',
    nameZh: '埼玉市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'saitama-city',
  },
  // ── Chiba 千葉県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_chiba',
    parentId: null,
    nameEn: 'Chiba',
    nameJa: '千葉県',
    nameZh: '千叶县',
    sortOrder: 12,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'chiba',
  },
  {
    id: 'reg_chiba_city',
    parentId: 'reg_chiba',
    nameEn: 'Chiba',
    nameJa: '千葉市',
    nameZh: '千叶市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'chiba-city',
  },
  // ── Tokyo 東京都 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_tokyo',
    parentId: null,
    nameEn: 'Tokyo',
    nameJa: '東京都',
    nameZh: '东京都',
    sortOrder: 13,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'tokyo',
  },
  {
    // Tokyo has no single "capital city"; its 23 special wards are the urban core
    // and the practical rental hub, so they stand in for the CITY node here.
    id: 'reg_tokyo_city',
    parentId: 'reg_tokyo',
    nameEn: 'Tokyo (23 Wards)',
    nameJa: '東京23区',
    nameZh: '东京23区',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'tokyo-city',
  },
  // ── Kanagawa 神奈川県 ─────────────────────────────────────────────────────────
  {
    id: 'reg_kanagawa',
    parentId: null,
    nameEn: 'Kanagawa',
    nameJa: '神奈川県',
    nameZh: '神奈川县',
    sortOrder: 14,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'kanagawa',
  },
  {
    id: 'reg_yokohama_city',
    parentId: 'reg_kanagawa',
    nameEn: 'Yokohama',
    nameJa: '横浜市',
    nameZh: '横滨市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'yokohama-city',
  },
  {
    id: 'reg_kawasaki_city',
    parentId: 'reg_kanagawa',
    nameEn: 'Kawasaki',
    nameJa: '川崎市',
    nameZh: '川崎市',
    sortOrder: 2,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kawasaki-city',
  },
  {
    id: 'reg_sagamihara_city',
    parentId: 'reg_kanagawa',
    nameEn: 'Sagamihara',
    nameJa: '相模原市',
    nameZh: '相模原市',
    sortOrder: 3,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'sagamihara-city',
  },
  // ── Niigata 新潟県 ────────────────────────────────────────────────────────────
  {
    id: 'reg_niigata',
    parentId: null,
    nameEn: 'Niigata',
    nameJa: '新潟県',
    nameZh: '新潟县',
    sortOrder: 15,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'niigata',
  },
  {
    id: 'reg_niigata_city',
    parentId: 'reg_niigata',
    nameEn: 'Niigata',
    nameJa: '新潟市',
    nameZh: '新潟市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'niigata-city',
  },
  // ── Toyama 富山県 ─────────────────────────────────────────────────────────────
  {
    id: 'reg_toyama',
    parentId: null,
    nameEn: 'Toyama',
    nameJa: '富山県',
    nameZh: '富山县',
    sortOrder: 16,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'toyama',
  },
  {
    id: 'reg_toyama_city',
    parentId: 'reg_toyama',
    nameEn: 'Toyama',
    nameJa: '富山市',
    nameZh: '富山市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'toyama-city',
  },
  // ── Ishikawa 石川県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_ishikawa',
    parentId: null,
    nameEn: 'Ishikawa',
    nameJa: '石川県',
    nameZh: '石川县',
    sortOrder: 17,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'ishikawa',
  },
  {
    id: 'reg_kanazawa_city',
    parentId: 'reg_ishikawa',
    nameEn: 'Kanazawa',
    nameJa: '金沢市',
    nameZh: '金泽市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kanazawa-city',
  },
  // ── Fukui 福井県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_fukui',
    parentId: null,
    nameEn: 'Fukui',
    nameJa: '福井県',
    nameZh: '福井县',
    sortOrder: 18,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'fukui',
  },
  {
    id: 'reg_fukui_city',
    parentId: 'reg_fukui',
    nameEn: 'Fukui',
    nameJa: '福井市',
    nameZh: '福井市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'fukui-city',
  },
  // ── Yamanashi 山梨県 ──────────────────────────────────────────────────────────
  {
    id: 'reg_yamanashi',
    parentId: null,
    nameEn: 'Yamanashi',
    nameJa: '山梨県',
    nameZh: '山梨县',
    sortOrder: 19,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'yamanashi',
  },
  {
    id: 'reg_kofu_city',
    parentId: 'reg_yamanashi',
    nameEn: 'Kofu',
    nameJa: '甲府市',
    nameZh: '甲府市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'kofu-city',
  },
  // ── Nagano 長野県 ─────────────────────────────────────────────────────────────
  {
    id: 'reg_nagano',
    parentId: null,
    nameEn: 'Nagano',
    nameJa: '長野県',
    nameZh: '长野县',
    sortOrder: 20,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'nagano',
  },
  {
    id: 'reg_nagano_city',
    parentId: 'reg_nagano',
    nameEn: 'Nagano',
    nameJa: '長野市',
    nameZh: '长野市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'nagano-city',
  },
  // ── Gifu 岐阜県 ───────────────────────────────────────────────────────────────
  {
    id: 'reg_gifu',
    parentId: null,
    nameEn: 'Gifu',
    nameJa: '岐阜県',
    nameZh: '岐阜县',
    sortOrder: 21,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'gifu',
  },
  {
    id: 'reg_gifu_city',
    parentId: 'reg_gifu',
    nameEn: 'Gifu',
    nameJa: '岐阜市',
    nameZh: '岐阜市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'gifu-city',
  },
  // ── Shizuoka 静岡県 ───────────────────────────────────────────────────────────
  {
    id: 'reg_shizuoka',
    parentId: null,
    nameEn: 'Shizuoka',
    nameJa: '静岡県',
    nameZh: '静冈县',
    sortOrder: 22,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'shizuoka',
  },
  {
    id: 'reg_shizuoka_city',
    parentId: 'reg_shizuoka',
    nameEn: 'Shizuoka',
    nameJa: '静岡市',
    nameZh: '静冈市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'shizuoka-city',
  },
  {
    id: 'reg_hamamatsu_city',
    parentId: 'reg_shizuoka',
    nameEn: 'Hamamatsu',
    nameJa: '浜松市',
    nameZh: '滨松市',
    sortOrder: 2,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'hamamatsu-city',
  },
  // ── Aichi 愛知県 ──────────────────────────────────────────────────────────────
  {
    id: 'reg_aichi',
    parentId: null,
    nameEn: 'Aichi',
    nameJa: '愛知県',
    nameZh: '爱知县',
    sortOrder: 23,
    type: 'PREFECTURE',
    latitude: null,
    longitude: null,
    assignable: false,
    slug: 'aichi',
  },
  {
    id: 'reg_nagoya_city',
    parentId: 'reg_aichi',
    nameEn: 'Nagoya',
    nameJa: '名古屋市',
    nameZh: '名古屋市',
    sortOrder: 1,
    type: 'CITY',
    latitude: null,
    longitude: null,
    assignable: true,
    slug: 'nagoya-city',
  },
] as const
